spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_travel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect